"""empty message

Revision ID: 073df3f1a96f
Revises: 8d6df4ff5466
Create Date: 2022-08-23 15:56:32.536811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '073df3f1a96f'
down_revision = '8d6df4ff5466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
