"""empty message

Revision ID: 4f5c12098ab3
Revises: 073df3f1a96f
Create Date: 2022-08-23 15:57:10.574362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5c12098ab3'
down_revision = '073df3f1a96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job')
    # ### end Alembic commands ###
